@startuml architecture

title "Banco de Dados e Componentes"

node "AWS" {
    component "User DB (PostgreSQL)" as user_db
    component "Scheduler DB (PostgreSQL)" as scheduler_db
    component "Appointments DB (PostgreSQL)" as appointments_db
    component "Cache (Redis)" as cache

    component "URL de Conexão User DB" as user_db_url
    component "URL de Conexão Scheduler DB" as scheduler_db_url
    component "URL de Conexão Appointments DB" as appointments_db_url
    component "URL de Conexão Cache" as cache_url

    user_db -down-> user_db_url
    scheduler_db -down-> scheduler_db_url
    appointments_db -down-> appointments_db_url
    cache -down-> cache_url
}

@enduml